"""Hawkes Process — self-exciting order flow model.

Models order arrival times as a self-exciting point process where
each trade raises the probability of the next one.

Key metric: the branching ratio (alpha/beta) — the fraction of orders
generated by prior orders rather than exogenous news.
- Normal: 0.5-0.7
- Hot market: 0.7-0.85
- Danger zone: > 0.85 (cascade risk)

When branching ratio jumps, the market is running hot.
A market maker should widen the spread, not tighten it.

Based on Hawkes (1971): lambda(t) = mu + sum(alpha * exp(-beta * (t - t_i)))
"""

from __future__ import annotations

import logging
from collections import deque
from dataclasses import dataclass

import numpy as np
from scipy.optimize import minimize

logger = logging.getLogger(__name__)

# Thresholds
BRANCHING_RATIO_HOT = 0.75
BRANCHING_RATIO_DANGER = 0.85
MIN_EVENTS = 50


@dataclass
class HawkesEstimate:
    """Result of Hawkes process estimation."""

    mu: float  # baseline intensity (events/sec)
    alpha: float  # excitation parameter
    beta: float  # decay parameter
    branching_ratio: float  # alpha/beta
    avg_intensity: float  # mu / (1 - branching_ratio)
    log_likelihood: float
    sample_size: int
    is_reliable: bool

    @property
    def is_hot(self) -> bool:
        return self.is_reliable and self.branching_ratio > BRANCHING_RATIO_HOT

    @property
    def is_danger(self) -> bool:
        return self.is_reliable and self.branching_ratio > BRANCHING_RATIO_DANGER

    @property
    def interpretation(self) -> str:
        if not self.is_reliable:
            return "Insufficient data"
        if self.branching_ratio > BRANCHING_RATIO_DANGER:
            return f"DANGER — cascade risk ({self.branching_ratio:.1%} endogenous)"
        if self.branching_ratio > BRANCHING_RATIO_HOT:
            return f"Hot market ({self.branching_ratio:.1%} endogenous) — widen spread"
        return f"Normal flow ({self.branching_ratio:.1%} endogenous)"

    def to_prompt_text(self) -> str:
        return (
            f"Order Flow: mu={self.mu:.4f}/s, branching={self.branching_ratio:.2f} "
            f"— {self.interpretation}"
        )


def _hawkes_neg_log_likelihood(
    params: np.ndarray, event_times: np.ndarray, T: float
) -> float:
    """Negative log-likelihood for a univariate Hawkes process.

    Uses O(n) recursive computation instead of O(n^2).
    """
    mu, alpha, beta = params

    if mu <= 0 or alpha <= 0 or beta <= 0 or alpha >= beta:
        return 1e10

    n = len(event_times)

    # Recursive intensity computation
    R = np.zeros(n)
    for i in range(1, n):
        dt = event_times[i] - event_times[i - 1]
        R[i] = np.exp(-beta * dt) * (1 + R[i - 1])

    # Compensator (integral of intensity)
    integral = mu * T + (alpha / beta) * np.sum(
        1 - np.exp(-beta * (T - event_times))
    )

    # Log-likelihood
    log_intensities = np.log(np.maximum(mu + alpha * R, 1e-10))
    ll = np.sum(log_intensities) - integral

    return -ll


class HawkesFlowEstimator:
    """Estimates Hawkes process parameters from order arrival times.

    Fits mu, alpha, beta via MLE with multiple random starts
    (the likelihood landscape is non-convex).
    """

    def __init__(self, max_events: int = 1000, n_starts: int = 5):
        self.max_events = max_events
        self.n_starts = n_starts
        # market_id -> deque of event timestamps (seconds)
        self._events: dict[str, deque[float]] = {}

    def record_event(self, market_id: str, timestamp: float) -> None:
        """Record a trade event timestamp."""
        if market_id not in self._events:
            self._events[market_id] = deque(maxlen=self.max_events)
        self._events[market_id].append(timestamp)

    def estimate(self, market_id: str) -> HawkesEstimate:
        """Fit Hawkes process to observed event times."""
        events = self._events.get(market_id)
        if not events or len(events) < MIN_EVENTS:
            return HawkesEstimate(
                mu=0, alpha=0, beta=0, branching_ratio=0,
                avg_intensity=0, log_likelihood=0,
                sample_size=len(events) if events else 0,
                is_reliable=False,
            )

        event_times = np.array(sorted(events))
        # Normalize to start at 0
        event_times = event_times - event_times[0]
        T = event_times[-1]

        if T <= 0:
            return HawkesEstimate(
                mu=0, alpha=0, beta=0, branching_ratio=0,
                avg_intensity=0, log_likelihood=0,
                sample_size=len(events), is_reliable=False,
            )

        best_result = None
        best_nll = np.inf

        for _ in range(self.n_starts):
            x0 = [
                np.random.uniform(0.1, 2.0),
                np.random.uniform(0.1, 0.8),
                np.random.uniform(1.0, 5.0),
            ]
            try:
                result = minimize(
                    _hawkes_neg_log_likelihood,
                    x0,
                    args=(event_times, T),
                    method="Nelder-Mead",
                    options={"xatol": 1e-6, "fatol": 1e-6, "maxiter": 5000},
                )
                if result.fun < best_nll:
                    best_nll = result.fun
                    best_result = result
            except Exception:
                continue

        if best_result is None:
            return HawkesEstimate(
                mu=0, alpha=0, beta=0, branching_ratio=0,
                avg_intensity=0, log_likelihood=0,
                sample_size=len(events), is_reliable=False,
            )

        mu, alpha, beta = best_result.x
        branching_ratio = alpha / beta if beta > 0 else 0

        estimate = HawkesEstimate(
            mu=mu,
            alpha=alpha,
            beta=beta,
            branching_ratio=branching_ratio,
            avg_intensity=mu / (1 - branching_ratio) if branching_ratio < 1 else float("inf"),
            log_likelihood=-best_nll,
            sample_size=len(events),
            is_reliable=(branching_ratio < 1.0 and len(events) >= MIN_EVENTS),
        )

        if estimate.is_danger:
            logger.warning(
                "Market %s: DANGER — branching ratio %.2f (cascade risk)",
                market_id, branching_ratio,
            )
        elif estimate.is_hot:
            logger.warning(
                "Market %s: Hot market — branching ratio %.2f",
                market_id, branching_ratio,
            )

        return estimate

    def clear_market(self, market_id: str) -> None:
        self._events.pop(market_id, None)
